#!/bin/sh

# Copyright (C) 2016 Adenops Consultants Informatique Inc.
#
# This file is part of the Moustack project, see http://www.moustack.org for
# more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# source shell library
. /usr/lib/runit/load

wait_for syslog
wait_for statd

# Uncomment this and add the two daemons if you need kerberos support.
# wait_for idmapd
# wait_for gssd

log "Mounting NFS filesystem"
mount -t nfsd nfsd /proc/fs/nfsd

log "Re-export all directories in /etc/exports"
exportfs -ra > /dev/null

log "stop existing nfsd kernel threads if any"
rpc.nfsd --debug 0

log "start nfsd kernel threads"
rpc.nfsd --debug ${NFSD_COUNT:-8}

exec rpc.mountd --foreground
