#!/bin/sh
set -eu

# populate the identity service database
su -s /bin/sh -c "keystone-manage db_sync" keystone

# ensure proper permissions on fernet key repositories folders
mkdir -p /etc/keystone/fernet-keys /etc/keystone/credential-keys
chown -R keystone:keystone /etc/keystone/fernet-keys /etc/keystone/credential-keys

# initialize fernet key repositories
keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
keystone-manage credential_setup --keystone-user keystone --keystone-group keystone

# execute bootstrap (password will be updated by the agent)
# TODO: this is temporary and will need some rework to remove hardcoded values
keystone-manage bootstrap \
     --bootstrap-username admin \
     --bootstrap-password admin \
     --bootstrap-region-id RegionOne
