#!/bin/sh

# Copyright (C) 2016 Adenops Consultants Informatique Inc.
#
# This file is part of the Moustack project, see http://www.moustack.org for
# more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Exit on failure
set -e

# Switch working directory
cd $(dirname $0)

# Avoid locale issues
export LC_ALL=C

# dpkg shouldn't ask questions
export DEBIAN_FRONTEND=noninteractive

# disable fsync from dpkg
echo force-unsafe-io > /etc/dpkg/dpkg.cfg.d/disable-fsync

# Configure main repository
cat >/etc/apt/sources.list <<EOF
deb http://archive.ubuntu.com/ubuntu/ xenial main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu xenial-security main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu/ xenial-updates main restricted universe multiverse
EOF

# Update packages list
apt-get update

# Install eatmydata
apt-get install -y --no-install-recommends \
	eatmydata

# Upgrade system
eatmydata apt-get dist-upgrade -y --no-install-recommends

# Install usefull packages
eatmydata apt-get install -y --no-install-recommends \
	apt-transport-https \
	bind9-host \
	ca-certificates \
	cron \
	curl \
	dnsutils \
	file \
	gawk \
	git \
	htop \
	iproute2 \
	iputils-arping \
	iputils-ping \
	jq \
	less \
	libltdl7 \
	netcat-openbsd \
	net-tools \
	openssl \
	patch \
	procps \
	psmisc \
	strace \
	tcpdump \
	telnet \
	uuid \
	vim-tiny \
	wget

# Install runit init system
eatmydata apt-get install -y --no-install-recommends \
	runit

# Install syslog server
eatmydata apt-get install -y --no-install-recommends \
	syslog-ng-core \
	logrotate

# Install gosu (sudo/su replacement)
GOSU_VERSION=1.9
http_proxy= gpg --keyserver ipv4.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
wget -O/usr/sbin/gosu     https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-$(dpkg --print-architecture)
wget -O/usr/sbin/gosu.asc https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-$(dpkg --print-architecture).asc
gpg --verify /usr/sbin/gosu.asc
rm -f /usr/sbin/gosu.asc
chmod a+x /usr/sbin/gosu

# Install tini (a tiny but valid init for containers)
TINI_VERSION=v0.14.0
http_proxy= gpg --keyserver ipv4.pool.sks-keyservers.net --recv-keys 0527A9B7
wget -O/usr/sbin/tini     https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini
wget -O/usr/sbin/tini.asc https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini.asc
gpg --verify /usr/sbin/tini.asc
rm -f /usr/sbin/tini.asc
chmod a+x /usr/sbin/tini

# Configure shell
cp bashrc ${HOME}/.bashrc

# Flush cron entries
find /etc/cron.* -type f -delete

# Make sure that inittab exists
touch /etc/inittab

# Clean rootfs
cd /
apt-get clean
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
