#!/bin/sh

# Copyright (C) 2016 Adenops Consultants Informatique Inc.
#
# This file is part of the Moustack project, see http://www.moustack.org for
# more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# exit on failure
set -e

# save environment variables
export >> /etc/environment

# run additionnal entrypoints
for ENTRYPOINT in `find /usr/sbin/ -name 'entrypoint-*' | sort -n`; do
	# echo to stderr is case 'docker run' is used in pipe for parsing
	echo "Running script ${ENTRYPOINT}" >&2

	# source/run entrypoint
	. ${ENTRYPOINT}
done

# a command has been specified, run it
if [ ! -z "$1" ]; then
	exec tini -g -- "$@"

# no runit service is configured, invoke bash
elif [ -z "`find /etc/service -name run`" ]; then
	exec /bin/bash

# start runit services
else
	exec tini -g -- /usr/sbin/runsvdir-start
fi
