#!/bin/sh

# Copyright (C) 2016 Adenops Consultants Informatique Inc.
#
# This file is part of the Moustack project, see http://www.moustack.org for
# more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# source shell library
. /usr/lib/runit/load

wait_for syslog
wait_for rabbitmq
wait_for neutron-server
wait_for designate-api

# create default domain for nova and neutron notifications
. /etc/openstack/variables

server_id=`designate server-list | awk '/'${designate_server_name}'\./ { print $2; }'`
domain_id=`designate domain-list | awk '/'${dhcp_domain}'\./ { print $2; }'`

if [ -z "${server_id}" ]; then
	designate server-create --name ${designate_server_name}.
	server_id=`designate server-list | awk '/'${designate_server_name}'\./ { print $2; }'`
fi

if [ -z "${domain_id}" ]; then
	designate domain-create --name ${dhcp_domain}. --email root@${dhcp_domain}
	domain_id=`designate domain-list | awk '/'${dhcp_domain}'\./ { print $2; }'`
fi

sed -ri "s/THIS_WILL_BE_REPLACED_BY_SINK_STARTUP_SCRIPT/${domain_id}/g" /etc/designate/designate-notifications.conf

service_start designate /usr/bin/designate-sink \
	--config-file=/etc/designate/designate.conf \
	--config-file=/etc/designate/designate-notifications.conf
