#!/bin/sh

# Copyright (C) 2016 Adenops Consultants Informatique Inc.
#
# This file is part of the Moustack project, see http://www.moustack.org for
# more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Exit on failure
set -e

# Switch working directory
cd $(dirname $0)

# Avoid locale issues
export LC_ALL=C

# dpkg shouldn't ask questions
export DEBIAN_FRONTEND=noninteractive

# Configure openstack repository
http_proxy= apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5EDB1B62EC4926EA
cat >/etc/apt/sources.list.d/openstack.list <<EOF
deb http://ubuntu-cloud.archive.canonical.com/ubuntu trusty-updates/liberty main
EOF

# Update packages list
apt-get update

# Upgrade system
eatmydata apt-get dist-upgrade -y --no-install-recommends

# Install and patch usefull python modules
eatmydata apt-get install -y --no-install-recommends \
	python-oslo.db \
	python-oslo.messaging \
	python-eventlet

patch -p1 -d /usr/lib/python2.7/dist-packages/ < /tmp/0001-reduce-eventlet-cpu-usage.patch

# Clean rootfs
cd /
#apt-get clean
#rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
rm -rf /tmp/* /var/tmp/*
