#!/bin/sh

# Copyright (C) 2016 Adenops Consultants Informatique Inc.
#
# This file is part of the Moustack project, see http://www.moustack.org for
# more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# source shell library
. /usr/lib/runit/load

wait_for syslog
wait_for openvswitch
wait_for neutron-server

# generate awk script
cat >/tmp/ovs-bridges.awk <<EOF
/^bridge_mappings/ {
	split(\$2, mappings, ",");

	for (i=1; i<=length(mappings); i++) {
		split(mappings[i], mapping, ":");

		if (length(mapping) == 2) {
			print mapping[2];
		};
	};
}
EOF

# wait for the PHYs to be plugged to the bridges
for bridge in `awk -F'[ \t=]+' -f /tmp/ovs-bridges.awk /etc/neutron/plugins/ml2/openvswitch_agent.ini`; do
	while ! ovs-vsctl list-ifaces $bridge 2>/dev/null | grep -q ^phy- ; do
		notify "wait for PHY to be plugged to OVS bridge $bridge"
		sleep 1
	done
done

exec nc -4kl 7778 > /dev/null
