#!/bin/sh

# Copyright (C) 2016 Adenops Consultants Informatique Inc.
#
# This file is part of the Moustack project, see http://www.moustack.org for
# more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# exit on failure
set -e

# redirect stderr to stdout (runit do not forward stderr to container's output)
exec 2>&1

# default environment variables
export LANG=C
export LC_ALL=C
export RUNIT_LIB=/usr/lib/runit

# source saved environment
. /etc/environment

# load libraries
. ${RUNIT_LIB}/service
. ${RUNIT_LIB}/logging

# show service startup if ran by runit
if [ "`basename $0`" = "run" ]; then
	show "starting"
fi
