#!/bin/sh

# Copyright (C) 2016 Adenops Consultants Informatique Inc.
#
# This file is part of the Moustack project, see http://www.moustack.org for
# more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# colors

if [ "${RUNIT_COLORIZE}" = "true" ]; then
	COLOR_RESTORE='\033[0m'
	COLOR_RED='\033[01;31m'
	COLOR_GREEN='\033[01;32m'
	COLOR_YELLOW='\033[01;33m'
	COLOR_BLUE='\033[01;34m'
else
	COLOR_RESTORE=
	COLOR_RED=
	COLOR_GREEN=
	COLOR_YELLOW=
	COLOR_BLUE=
fi

# functions

fatal() {
	/bin/echo -e "${COLOR_RED}`service_name`: $*${COLOR_RESTORE}"
	exit 1
}

warn() {
	/bin/echo -e "${COLOR_YELLOW}`service_name`: $*${COLOR_RESTORE}"
}

notify() {
	/bin/echo -e "${COLOR_BLUE}`service_name`: $*${COLOR_RESTORE}"
}

show() {
	/bin/echo -e "${COLOR_GREEN}`service_name`: $*${COLOR_RESTORE}"
}

log() {
	/bin/echo -e "`service_name`: $*"
}
