#!/bin/sh

# Copyright (C) 2016 Adenops Consultants Informatique Inc.
#
# This file is part of the Moustack project, see http://www.moustack.org for
# more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# source shell library
. /usr/lib/runit/load

wait_for syslog

while ! sv status ovsdb-server >/dev/null 2>&1; do
	notify "wait for OVS service to be up"
	sleep 1
done

# have OVSDB listening for connections on port 6640
ovs-appctl -t ovsdb-server ovsdb-server/add-remote ptcp:6640

exec ovs-vswitchd \
	unix:/var/run/openvswitch/db.sock \
	-vconsole:info \
	--no-chdir \
	--pidfile=/var/run/openvswitch/ovs-vswitchd.pid

# XXX: --mlockall currently omitted, will see later...
# to be able to use it, use the following docker parameters:
#  --cap-add=IPC_LOCK --ulimit memlock=-1:-1
