#!/bin/sh

# Copyright (C) 2016 Adenops Consultants Informatique Inc.
#
# This file is part of the Moustack project, see http://www.moustack.org for
# more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Exit on failure
set -e

# Switch working directory
cd $(dirname $0)

# Avoid locale issues
export LC_ALL=C

# dpkg shouldn't ask questions
export DEBIAN_FRONTEND=noninteractive

# Configure logstash repository
apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-keys 46095ACC8548582C1A2699A9D27D666CD88E42B4
cat >/etc/apt/sources.list.d/logstash.list <<EOF
deb http://packages.elastic.co/logstash/2.1/debian stable main
EOF

# Update packages list
apt-get update

# Install and patch usefull python modules
eatmydata apt-get install -y --no-install-recommends \
	apache2 \
	libapache2-mod-php5 \
	logstash \
	openjdk-7-jre-headless

# Purge useless apache configuration
rm -f /etc/apache2/sites-enabled/*
rm -f /etc/apache2/conf-enabled/serve-cgi-bin.conf
rm -f /etc/apache2/conf-enabled/openstack-dashboard.conf
rm -f /etc/apache2/conf-enabled/other-vhosts-access-log.conf

# Remove default landing page
rm -f /var/www/html/index.html

# Install PimpMyLog
curl -L https://github.com/potsky/PimpMyLog/archive/v1.7.10.tar.gz | tar xvz --strip-components=1 -C /var/www/html/

# Clean rootfs
cd /
apt-get clean
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
