#!/bin/sh

# Copyright (C) 2016 Adenops Consultants Informatique Inc.
#
# This file is part of the Moustack project, see http://www.moustack.org for
# more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# XXX: all this user logic is messy, is this (or some part of it) related to
# our dev environment? Is all of this relevant on a server?
# It seems it could also mess up live migration, libvirt and nova user have to
# be the same everywhere, so we should probably solve it during docker build.

# source shell library
. /usr/lib/runit/load

wait_for syslog

exec virtlogd --verbose
