#!/bin/sh

# exit on failure
set -e

# exit on unassigned variables
set -u

# switch to current directory
cd $(dirname $0)

# default variables
base="moustack-base"
domain="cloud.local"
registry="172.30.0.254"

# define usage
usage() {
	echo "usage: $0 [-h] [-n] [-d] [-u] [-p] [-r] [-s]"
	echo
	echo "	-h	show this help message"
	echo "	-b	base container name (default: ${base})"
	echo "	-n	container name"
	echo "	-d	domain name (default: ${domain})"
	echo "	-m	MAC addresses prefix"
	echo "	-r	local docker registry IP address (default: ${registry})"
	echo
	exit ${1:-0}
}

# define colorized log
logme() {
	/bin/echo -e "\n\033[1;32m--- $@ ---\033[0m\n"
}

while getopts "hb:n:d:m:r:" opt; do
	case $opt in
		h) usage 0;;
		b) base="${OPTARG}" ;;
		n) name="${OPTARG}" ;;
		d) domain="${OPTARG}" ;;
		m) mac="${OPTARG}" ;;
		r) registry="${OPTARG}" ;;
		*) usage 1;;
	esac
done

if [ "`id -u`" -ne 0 ]; then
	echo "Please run as root or use sudo"
	exit 1
elif [ "${#}" -eq 0 ]; then
	usage 1
elif [ -z "${name:-}" ]; then
	echo "You must set a container name"
	exit 1
elif [ -z "${mac:-}" ]; then
	echo "You must set a MAC address prefix"
	exit 1
fi

logme "create ${name} container from ${base}"
rsync -a /var/lib/lxc/${base}/ /var/lib/lxc/${name}

logme "create container configuration"
sed "s/\${CONTAINER_NAME}/${name}/g; s/\${CONTAINER_BASE}/${base}/g; s/\${MAC_PREFIX}/${mac}/g;" ./config.moustack.template >/var/lib/lxc/${name}/config

logme "remove default network interfaces configuration"
cat >/var/lib/lxc/${name}/rootfs/etc/network/interfaces <<EOF
# The loopback network interface
auto lo
iface lo inet loopback

# TODO: eth0 configuration
EOF

logme "generation resolv.conf"
cat >/var/lib/lxc/${name}/rootfs/etc/resolv.conf <<EOF
search ${domain}
domain ${domain}

# TODO: nameservers configuration
EOF

logme "configure hostname"
echo ${name} >/var/lib/lxc/${name}/rootfs/etc/hostname

cat >/var/lib/lxc/${name}/rootfs/etc/hosts <<EOF
127.0.0.1	localhost
127.0.1.1	${name}.${domain} ${name}

${registry}	local-registry

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
EOF

logme "start container to make final checks"
lxc-start -n ${name}

while ! lxc-attach -n ${name} -- true; do
	echo "waiting for container to be ready"
	sleep 1
done

logme "check docker status"
while ! lxc-attach -n ${name} -- docker ps; do
	echo "waiting for nested docker daemon to be ready"
	sleep 1
done

logme "stop container"
lxc-stop -n ${name}
