#!/bin/sh
set -eu

# populate the nova-api database
su -s /bin/sh -c "nova-manage api_db sync" nova

# register the cell0 database
su -s /bin/sh -c "nova-manage cell_v2 map_cell0" nova

# create the cell1 cell
# TODO: move to agent?
if ! su -s /bin/sh -c "nova-manage cell_v2 list_cells" nova | grep -q '| cell1 |'; then
	su -s /bin/sh -c "nova-manage cell_v2 create_cell --name=cell1 --verbose" nova
fi

# populate the nova database
su -s /bin/sh -c "nova-manage db sync" nova
