#!/bin/sh

# Copyright (C) 2016 Adenops Consultants Informatique Inc.
#
# This file is part of the Moustack project, see http://www.moustack.org for
# more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# source shell library
. /usr/lib/runit/load

# create and fix permissions on default syslog-docker file
#
# note: this is required to avoid the "has been replaced with a remote file.
# giving up on this name" issue with tail

logfile=/var/log/syslog-docker

touch ${logfile}
chmod 0640 ${logfile}
chown root:adm ${logfile}

exec tail --follow=name --retry -n 0 ${logfile}
