#!/bin/sh

# Copyright (C) 2016 Adenops Consultants Informatique Inc.
#
# This file is part of the Moustack project, see http://www.moustack.org for
# more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# source shell library
. /usr/lib/runit/load

wait_for syslog
wait_for openvswitch
wait_for rabbitmq
wait_for neutron-server
wait_for libvirt

# fix /dev/kvm permissions
kvm_host_group=kvm-host
kvm_user=nova

if ! grep -q "${kvm_host_group}:" /etc/group; then
	groupadd --gid `ls -l /dev/kvm | awk '{ print $4; }'` ${kvm_host_group}
fi

if ! grep -q "${kvm_host_group}:.*${kvm_user}" /etc/group; then
	adduser ${kvm_user} ${kvm_host_group}
fi

# ensure instances folder is created (nova may fail otherwise)
service_mkdir nova /var/lib/nova/instances

service_start nova /usr/bin/nova-compute --config-file=/etc/nova/nova.conf
