#!/bin/sh

# Copyright (C) 2016 Adenops Consultants Informatique Inc.
#
# This file is part of the Moustack project, see http://www.moustack.org for
# more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Exit on failure
set -e

# Switch working directory
cd $(dirname $0)

# Avoid locale issues
export LC_ALL=C

# dpkg shouldn't ask questions
export DEBIAN_FRONTEND=noninteractive

# Update packages list
apt-get update

# Install required packages
eatmydata apt-get install -y --no-install-recommends \
	cifs-utils \
	nfs-common \
	nova-compute \
	ceilometer-agent-compute \
	openvswitch-switch \
	sysfsutils \
	libvirt-bin

# Purge nova local database
rm -f /var/lib/nova/nova.sqlite

# Remove libvirtd default network
rm -f /etc/libvirt/qemu/networks/autostart/default.xml

# Force uid and gid for nova, so we can more easily sync it with libvirt image
usermod -u 1200 nova
groupmod -g 1200 nova
chown -R nova:nova /etc/nova/ /var/lib/nova/

# Clean rootfs
cd /
apt-get clean
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
