#!/bin/sh

# Copyright (C) 2016 Adenops Consultants Informatique Inc.
#
# This file is part of the Moustack project, see http://www.moustack.org for
# more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

MDNS_HOST="${MDNS_HOST:-127.0.0.1}"
MDNS_PORT="${MDNS_PORT:-5354}"

echo "$1: waiting for Designate mDNS server..."

while ! nc -w 1 ${MDNS_HOST} ${MDNS_PORT} </dev/null >/dev/null; do sleep 1; done
