#!/bin/sh

# Copyright (C) 2016 Adenops Consultants Informatique Inc.
#
# This file is part of the Moustack project, see http://www.moustack.org for
# more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
KEYSTONE_HOST=${KEYSTONE_HOST:-127.0.0.1}
KEYSTONE_PORT=${KEYSTONE_PORT:-5000}

echo "$1: waiting for keystone..."
while [ "$(curl -s -o /dev/null -w '%{http_code}' $KEYSTONE_HOST:$KEYSTONE_PORT/v3 2>/dev/null)" != "200" ]
do
	sleep 1
done
