#!/bin/sh

# Copyright (C) 2016 Adenops Consultants Informatique Inc.
#
# This file is part of the Moustack project, see http://www.moustack.org for
# more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
MEMCACHED_HOST=${MEMCACHED_HOST:-127.0.0.1}
MEMCACHED_PORT=${MEMCACHED_PORT:-11211}

echo "$1: waiting for Memcached..."
while ! echo version | nc -w 2 $MEMCACHED_HOST $MEMCACHED_PORT 2>/dev/null | grep -q '^VERSION '
do
	sleep 1
done
